cart/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('cart.views',
                       url(r'^$', 'show_cart', { 'template_name': 'cart/cart.html'}, 'show_cart'),
                       )

ecomstore/urls.py
# from django.conf.urls import include, url
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

import settings

# from catalog import urls

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
#     # url(r'^catalog/$', catalog),
#     # url(r'^catalog/$', 'preview.views.home'),
#     url(r'^', include('catalog.urls')),
#     (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
# ]

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'specstali.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    # (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
)


# handler500 = 'views.file_not_found_404'
# handler400 = 'views.file_not_found_404'
# handler403 = 'views.file_not_found_404'
handler404 = 'ecomstore.views.file_not_found_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from django.db import models
from django.contrib.auth.models import User


class SearchTerm(models.Model):
    q = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True)
    tracking_id = models.CharField(max_length=50, default='')

    def __unicode__(self):
        return self.q

templates/tags/cart_box.html
{% with cart_item_count as cart_count %}
    <a href="{% url "show_cart" %}">
        Shopping Cart
        <br/>
        {{ cart_count }} Item{{ cart_count|pluralize }}
    </a>
{% endwith %}

templates/tags/category_list.html
{#<h3>Categories</h3>#}
{#{% for c in active_categories %}#}
{#    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a><br/>#}
{#{% endfor %}#}

<h3>Categories</h3>
<ul id="categories">
    {% with active_categories as cats %}
        {% for c in cats %}
            <li>
                {% ifequal c.get_absolute_url request_path %}
                    {{ c.name }}<br/>
                {% else %}
                    <a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a><br/>
                {% endifequal %}
            </li>
        {% endfor %}
    {% endwith %}
</ul>

templates/tags/footer.html
<a href="{% url "catalog_home" %}">Home</a>
{% with flatpage_list as pages %}
    {% for page in pages %}
        <a href="{{ page.url }}">{{ page.title }}</a>
    {% endfor %}
{% endwith %}
<a href="{% url "show_cart" %}">Shopping Cart</a>
<a href="{% url "tag_cloud" %}">Tag Cloud</a>

templates/tags/form_table_row.html
<tr>
    <th>
        {% if form_field.field.required %}*{% endif %}
        {{ form_field.label_tag }}
    </th>
    <td>
        {% if form_field.errors %}
            <ul class="errorlist">
                {% for error in form_field.errors %}
                    <li>{{ form_field.label }}: {{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {{ form_field }}
    </td>
</tr>

templates/tags/navigation.html
{#<ul>#}
{#    <li><a href="/catalog/">Home</a></li>#}
{#    <li><a href="/catalog/">About</a></li>#}
{#    <li><a href="/catalog/">Privacy</a></li>#}
{#    <li><a href="/catalog/">Products</a></li>#}
{#    <li><a href="/catalog/">Contact</a></li>#}
{#</ul>#}
{#<div class="cb"></div>#}
<ul>
    <li><a href="{% url "catalog_home" %}">Home</a></li>
    <li><a href="/about/">About</a></li>
    <li><a href="/privacy-policy/">Privacy</a></li>
    <li><a href="/contact/">Contact</a></li>
    <li>
        <a href="{% url "my_account" %}">My Account</a>
    </li>
</ul>
<div class="fr">
    <ul>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url "django.contrib.auth.views.logout" %}">Logout</a>
            {% else %}
                <a href="{% url "register" %}">Sign Up</a>
                </li>
                <li>
                <a href="{% url "django.contrib.auth.views.login" %}">Login</a>
            {% endif %}
            </li>
    </ul>
</div>
<div class="cb"></div>

templates/tags/pagination_links.html
{% if p.has_other_pages %}
    {% if p.has_previous %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">
            &laquo; Previous
        </a>
    {% else %}
        &laquo; Previous
    {% endif %}
    | Page {{ p.number }} of {{ paginator.num_pages }} |
    {% if p.has_next %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">
            Next &raquo;
        </a>
    {% else %}
        Next &raquo;
    {% endif %}
{% endif %}

templates/tags/product_list.html
{% for p in products %}
    {% if forloop.first %}
        <h3>{{ header_text }}</h3>
    {% endif %}
    {% include 'tags/product_thumbnail.html' %}
    {% if forloop.last %}
        <div class="cb">&nbsp;</div>
    {% endif %}
{% endfor %}

templates/tags/product_thumbnail.html
<div class="product_thumbnail">
    <a href="{{ p.get_absolute_url }}">
        <img src="{{ p.thumbnail.url }}" alt="{{ p.name }}" class="bn" width="100px"/>
        <br/>
        {{ p.name }}
    </a>
</div>

templates/tags/search_box.html
<form id="search" action="{% url "search_results" %}" method="get">
    <h3><label for="id_q">Search</label></h3>
    <div style="text-align:right;">
        {{ form.q }}
        <input type="submit" value="Search"/>
    </div>
</form>