cart/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('cart.views',
                       url(r'^$', 'show_cart', { 'template_name': 'cart/cart.html'}, 'show_cart'),
                       )

catalog/urls.py
# from django.conf.urls.defaults import *
from django.conf.urls import include, url, patterns


urlpatterns = patterns('catalog.views',
               url(r'^$', 'index', {'template_name': 'catalog/index.html'}, 'catalog_home'),
               url(r'^category/(?P<category_slug>[-\w]+)/$', 'show_category', {'template_name': 'catalog/category.html'}, 'catalog_category'),
               url(r'^product/(?P<product_slug>[-\w]+)/$', 'show_product', {'template_name': 'catalog/product.html'}, 'catalog_product'),
               url(r'^review/product/add/$', 'add_review'),
               url(r'^tag/product/add/$', 'add_tag'),
               url(r'^tag_cloud/$', 'tag_cloud', {'template_name': 'catalog/tag_cloud.html'}, 'tag_cloud'),
               url(r'^tag/(?P<tag>[-\w]+)/$', 'tag', {'template_name': 'catalog/tag.html'}, 'tag'),
               url(r'^review/product/add/$', 'add_review', {}, 'product_add_review'),
               )

ecomstore/urls.py
# from django.conf.urls import include, url
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

import settings

# from catalog import urls

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
#     # url(r'^catalog/$', catalog),
#     # url(r'^catalog/$', 'preview.views.home'),
#     url(r'^', include('catalog.urls')),
#     (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
# ]

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'specstali.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    # (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
)


# handler500 = 'views.file_not_found_404'
# handler400 = 'views.file_not_found_404'
# handler403 = 'views.file_not_found_404'
handler404 = 'ecomstore.views.file_not_found_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from tagging.registry import register


class ActiveCategoryManager(models.Manager):
    def get_query_set(self):
        return super(ActiveCategoryManager, self).get_query_set().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords", max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    active = ActiveCategoryManager()

    class Meta:
        db_table = 'categories'
        # ordering = ['-created_at']
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('catalog_category', (), { 'category_slug': self.slug })


class ActiveProductManager(models.Manager):
    def get_query_set(self):
        return super(ActiveProductManager, self).get_query_set().filter(is_active=True)


class FeaturedProductManager(models.Manager):
    def all(self):
        return super(FeaturedProductManager, self).all().filter(is_active=True).filter(is_featured=True)


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    brand = models.CharField(max_length=50)
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    old_price = models.DecimalField(max_digits=9,decimal_places=2,
                                    blank=True,default=0.00)
    # image = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/products/main')
    thumbnail = models.ImageField(upload_to='images/products/thumbnails')
    image_caption = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    quantity = models.IntegerField()
    description = models.TextField()
    meta_keywords = models.CharField(max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)

    objects = models.Manager()
    active = ActiveProductManager()

    featured = FeaturedProductManager()

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('catalog_product', (), { 'product_slug': self.slug })

    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

    def results(request):
        search_text = request.GET.get('q','')
        results = Product.objects.filter(name__icontains=search_text)
        return results # via render_to_response, of course

    def cross_sells(self):
        from checkout.models import Order, OrderItem
        orders = Order.objects.filter(orderitem__product=self)
        order_items = OrderItem.objects.filter(order__in=orders).exclude(product=self)
        products = Product.active.filter(orderitem__in=order_items).distinct()
        return products

    def cross_sells_user(self):
        from checkout.models import Order, OrderItem
        from django.contrib.auth.models import User
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter(order__user__in=users).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products

    def cross_sells_hybrid(self):
        from checkout.models import Order, OrderItem
        from django.contrib.auth.models import User
        from django.db.models import Q
        orders = Order.objects.filter(orderitem__product=self)
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter( Q(order__in=orders) |
                                          Q(order__user__in=users)).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products


# Product model class definition here
register(Product)


from django.contrib.auth.models import User


class ActiveProductReviewManager(models.Manager):
    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved=True)


class ProductReview(models.Model):
    RATINGS = ((5,5),(4,4),(3,3),(2,2),(1,1),)
    product = models.ForeignKey(Product)
    user = models.ForeignKey(User)
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(default=5, choices=RATINGS)
    is_approved = models.BooleanField(default=True)
    content = models.TextField()

    objects = models.Manager()
    approved = ActiveProductReviewManager()

catalog/forms.py
from django import forms
from catalog.models import Product, ProductReview


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero.')
        return self.cleaned_data['price']


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        exclude = ('user','product', 'is_approved')

# class ProductAddToCartForm(forms.Form):
#     quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size': '2',
#                                 'value': '1', 'class': 'quantity', 'maxlength': '5'}),
#                                 error_messages={'invalid': 'Please enter a valid quantity.'}, min_value=1)
#     product_slug = forms.CharField(widget=forms.HiddenInput())
#
#     # override the default __init__ so we can set the request
#     def __init__(self, request=None, *args, **kwargs):
#         self.request = request
#         super(ProductAddToCartForm, self).__init__(*args, **kwargs)
#
#     # custom validation to check for cookies
#     def clean(self):
#         if self.request:
#             if not self.request.session.test_cookie_worked():
#                 raise forms.ValidationError("Cookies must be enabled.")
#         return self.cleaned_data

catalog/views.py
from django.http import HttpResponseRedirect
from cart.forms import ProductAddToCartForm
from cart import cartpy
from django.shortcuts import get_object_or_404, render_to_response
from catalog.models import Category, Product, ProductReview
from catalog.forms import ProductReviewForm
from django.template import RequestContext
from django.core import urlresolvers

from stats import statspy as stats
from ecomstore.settings import PRODUCTS_PER_ROW


from django.http import HttpResponse
from django.core import serializers

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.template.loader import render_to_string
# from django.utils import simplejson
import json as simplejson
from django.http import HttpResponse
import tagging

from tagging.models import Tag, TaggedItem


def tag_cloud(request, template_name="catalog/tag_cloud.html"):
    product_tags = Tag.objects.cloud_for_model(Product, steps=9,distribution=tagging.utils.LOGARITHMIC,filters={ 'is_active': True })
    page_title = 'Product Tag Cloud'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def tag(request, tag, template_name="catalog/tag.html"):
    products = TaggedItem.objects.get_by_model(Product.active, tag)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

@login_required
def add_tag(request):
    print "dd tag"
    tags = request.POST.get('tag','')
    slug = request.POST.get('slug','')
    print  tags
    print  slug
    print  len(tags)
    if len(tags) > 2:
        p = Product.active.get(slug=slug)
        html = u''
        template = "catalog/tag_link.html"
        for tag in tags.split():
            tag.strip(',')
            Tag.objects.add_tag(p,tag)
        for tag in p.tags:
        # for tag in Tag.objects.all():
            html += render_to_string(template, {'tag': tag })
        print html
        response = simplejson.dumps({'success': 'True', 'html': html })
        print response
    else:
        response = simplejson.dumps({'success': 'False'})
    return HttpResponse(response, content_type='application/javascript; charset=utf8')

@login_required
@csrf_protect
def add_review(request):
    form = ProductReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        slug = request.POST.get('slug')
        product = Product.active.get(slug=slug)
        review.user = request.user
        review.product = product
        review.save()
        template = "catalog/product_review.html"
        html = render_to_string(template, {'review': review })
        response = simplejson.dumps({'success':'True', 'html': html})
    else:
        html = form.errors.as_ul()
        response = simplejson.dumps({'success':'False', 'html': html})
    return HttpResponse(response, content_type='application/javascript; charset=utf-8')


def get_json_products(request):
    products = Product.active.all()
    json_products = serializers.serialize("json", products)
    return HttpResponse(json_products, content_type='application/javascript; charset=utf-8')


def index(request, template_name="catalog/index.html"):
    search_recs = stats.recommended_from_search(request)
    featured = Product.featured.all()[0:PRODUCTS_PER_ROW]
    recently_viewed = stats.get_recently_viewed(request)
    view_recs = stats.recommended_from_views(request)
    page_title = 'Musical Instruments and Sheet Music for Musicians'
    # return get_json_products(request)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def show_category(request, category_slug, template_name="catalog/category.html"):
    c = get_object_or_404(Category, slug=category_slug)
    products = c.product_set.all()
    page_title = c.name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


# def show_product(request, product_slug, template_name="catalog/product.html"):
#     p = get_object_or_404(Product, slug=product_slug)
#     categories = p.categories.filter(is_active=True)
#     page_title = p.name
#     meta_keywords = p.meta_keywords
#     meta_description = p.meta_description
#     return render_to_response(template_name, locals(),context_instance=RequestContext(request))

# new product view, with POST vs GET detection
def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.all()
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    # need to evaluate the HTTP method
    if request.method == 'POST':
        # add to cart...create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        # check if posted data is valid
        if form.is_valid():
            # add to cart and redirect to cart page
            cartpy.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
                url = urlresolvers.reverse('show_cart')
                return HttpResponseRedirect(url)
    else:
        form = ProductAddToCartForm(request=request, label_suffix=':')
        # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
        # set the test cookie on our first GET request
    request.session.set_test_cookie()

    from stats import statspy as stats
    stats.log_product_view(request, p) # add to product view

    product_reviews = ProductReview.approved.filter(product=p).order_by('-date')
    review_form = ProductReviewForm()

    return render_to_response("catalog/product.html", locals(),context_instance=RequestContext(request))

templates/catalog/category.html
{% extends "catalog.html" %}
{% block content %}
    <h1>{{ c.name }}</h1>
    {{ c.description }}
    <br/><br/>
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
    {% endfor %}
{% endblock %}

templates/catalog/index.html
{% extends "catalog.html" %}
{% load catalog_tags %}
{% block content %}
<h1>Welcome to Modern Musician!</h1>
{% product_list recently_viewed 'Your Recently Viewed' %}
{% product_list view_recs 'Similar Products' %}
{% product_list featured 'Featured Products' %}
{% product_list search_recs 'Recommended For You' %}
{% endblock %}

templates/catalog/product.html
{% extends "catalog.html" %}
{% block content %}
    <div class="product_image">
       <img src="{{ p.image.url }}" alt="{{ p.name }}" />
    </div>
    <h1>{{ p.name }}</h1>
    Brand: <em>{{ p.brand }}</em>
    <br/><br/>
    SKU: {{ p.sku }}
    <br/>
    In categor{{ categories.count|pluralize:"y,ies" }}:
    {% for c in categories %}
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br/><br/>
    {% if p.sale_price %}
        Was:
        <del>$ {{ p.old_price }}</del>
        <br/>
        Now: $ {{ p.price }}
    {% else %}
        Price: $ {{ p.price }}
    {% endif %}
    <br/><br/>

    <form method="post" action="." class="cart">
        {% csrf_token %}
{#        <ul class="errorlist">#}
{#            <li>Please enter a valid quantity.</li>#}
{#        </ul>#}
{#        <label for="quantity">Quantity</label><input type="text" id="quantity" value="1" />#}
        {{ form.as_p }}
        <br/>
        <input type="submit" value="Add To Cart" name="submit" alt="Add To Cart"/>
    </form>
    <div class="cb"></div>
    <br/><br/>
    <div class="cb"><br/><br/></div>
    <h3>Related Products</h3>
    {% for p in p.cross_sells_hybrid %}
        {% include 'tags/product_thumbnail.html' %}
    {% empty %}
        No related products.
    {% endfor %}
    <div class="cb"></div>
    <h3>Product Description</h3>
    {{ p.description }}

{#    <div class="cb"><br /><br /></div>#}


    <div class="cb"><br/><br/></div>
    <h3>Product Tags</h3>
    <div id="tags">
        {% for tag in p.tags %}
            {% include 'catalog/tag_link.html' %}
        {% endfor %}
    </div>
    <br/>
    {% if request.user.is_authenticated %}
        <label for="id_tag">Tag this product (must be at least three
            characters):</label>
        <br/>
        <input id="id_tag" type="text"/>
        <input type="submit" value="Tag It" id="add_tag"/>
    {% else %}
        <a href="{% url "login" %}?next={{ request.path }}">
            Log in to tag this product.
        </a>
    {% endif %}
    <div class="cb"><br/><br/></div>




    <h3>Product Reviews</h3>
    {% if request.user.is_authenticated %}
    <a id="add_review">Write a Review</a>
    <div id="review_form">
        <div id="review_errors"></div>
        <table>
            {% csrf_token %}
            {{ review_form.as_table }}
            <tr>
                <td colspan="2">
                    <input type="hidden" id="id_slug" value="{{ p.slug }}"/>
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}"/>
                    <input type="submit" id="submit_review" value="Submit"/>
                    <input type="submit" id="cancel_review" value="Cancel"/>
                </td>
            </tr>
        </table>
    </div>
    {% else %}
        <a href="{% url "login" %}?next={{ request.path }}">
            Log in to write your own review.
        </a>
    {% endif %}
    <div class="cb"><br/><br/></div>
    <div id="reviews">
        {% for review in product_reviews %}
            {% include 'catalog/product_review.html' %}
        {% empty %}
            <div id="no_reviews">
                No product reviews yet.
            </div>
        {% endfor %}
    </div>
    <div class="cb"><br/><br/></div>
{% endblock %}

templates/catalog/product_review.html
<div class="review">
    Rating: {{ review.rating }}
    <strong>{{ review.title }}</strong>
    by {{ review.user.username }}
    <br/>
    {{ review.content }}
    <br/><br/>
    <hr/>
</div>

templates/catalog/tag.html
{% extends "catalog.html" %}
{% block content %}
    <h1>Products tagged with: '{{ tag }}'</h1>
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
    {% endfor %}
{% endblock %}

templates/catalog/tag_cloud.html
{% extends "catalog.html" %}
{% load tagging_tags %}
{% block content %}
    <h1>Product Tag Cloud</h1>
    {% for tag in product_tags %}
        <a href="/tag/{{ tag.name }}/" style="font-size:
                {{ tag.font_size|add:"11" }}px;">{{ tag.name|slugify }}</a>&nbsp;
    {% endfor %}
{% endblock %}

templates/catalog/tag_link.html
<a href="/tag/{{ tag.name }}/">{{ tag.name|slugify }}</a>&nbsp;